version: '3.5'

networks:
  default:
    name: bot_maker
    external: true
services:
  app_bot_maker:
    build: .
    image: bot_maker
    ports:
      - "9090:9090"
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
    command: uvicorn app.start_bet_maker:app --host 0.0.0.0 --port 9090 --reload
    networks:
      - default
    environment:
      - DEBUG=True
      - PROJECT_NAME=BOT_API
      - RABBITMQ_HOST=localhost
      - RABBITMQ_PORT=5672
      - RABBITMQ_LOGIN=user
      - RABBITMQ_PASSWORD=user
      - SERVER_NAME=BOT_API
      - SERVER_HOST=http://localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=anihortes
      - POSTGRES_SERVER=postgresql_db_bot_maker
      - POSTGRES_DB=postgres
      - LOGGER_ROTATION=10 MB
      - LOGGER_COMPRESSION=zip
      - LOGGER_DEBUG=True
      - REDIS_PORT=6378
      - REDIS_HOST=rq_redis
    tty: true
    stdin_open: true
    dns:
      - 0.0.0.0

  app_line_provider:
    build: .
    image: line_provider
    ports:
      - "9091:9090"
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
    command: uvicorn app.start_line_provider:app --host 0.0.0.0 --port 9090 --reload

    environment:
      - DEBUG=True
      - PROJECT_NAME=BOT_API
      - RABBITMQ_HOST=localhost
      - RABBITMQ_PORT=5672
      - RABBITMQ_LOGIN=user
      - RABBITMQ_PASSWORD=user
      - SERVER_NAME=BOT_API
      - SERVER_HOST=http://localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=anihortes
      - POSTGRES_SERVER=postgresql_db_bot_maker
      - POSTGRES_DB=postgres
      - LOGGER_ROTATION=10 MB
      - LOGGER_COMPRESSION=zip
      - LOGGER_DEBUG=True
      - REDIS_PORT=6378
      - REDIS_HOST=rq_redis
    tty: true
    stdin_open: true
    dns:
      - 0.0.0.0
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_bot_maker
    hostname: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "user"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia/
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - default
    dns:
      - 0.0.0.0
  db:
    container_name: postgresql_db_bot_maker
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    # env_file:
    #   - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=anihortes
      - POSTGRES_SERVER=postgresql_db
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - default
    dns:
      - 0.0.0.0

volumes:
  postgres_data:
